### ISSUE TITLE
refactor coupons component to accomodate recent changes in datahub

### ISSUE THREAD

**Issue by thesanjeevsharma** [dailykit/subscription-shop#66]
1. Now, when the condition is `null` datahub will return `true` for `isValid`. Remove checks from FE.
2. Enable apply button to be clicked even if a single reward is valid in case of multiple rewards.

ref: https://github.com/dailykit/dailyos/issues/533

**Comment by thesanjeevsharma** [comment]
Cases:
1. If multiple rewards allowed:
   - apply button will be active even if a single reward is valid
   - upon applying, valid rewards will be rewarded
2. If multiple rewards *not* allowed:
   - reward with the highest priority will be considered
   - apply button will be active when that reward is valid
   - upon applying, that reward will be rewarded
   
@ananya-rajput is this fine?

**Comment by ananya-rajput** [comment]
Yes. almost. one addition and correction just to be sure:
Addition:
1. If multiple rewards allowed
- all the rewards will be rewarded that are valid on applying the coupon

Correction:
2. If multiple rewards not allowed
- apply button will be active when any reward is valid among all
- the valid reward with the highest priority among the valid rewards will be shown on the store to be applied.
i.e.: first we will check the rewards that are valid and then we will check the highest priority among the valid rewards and show it on the store to be applied.
@thesanjeevsharma
