### ISSUE TITLE
Error while registering

### ISSUE THREAD

**Issue by roshandailykit** [dailykit/subscription-shop#76]
![Screenshot 2021-04-02 at 8 58 38 PM](https://user-images.githubusercontent.com/63472065/113429536-527b9200-93f6-11eb-8d51-4c0f62b41ae7.png)

While registering as a new customer, the address does not save but instead gives a strange error and freezes 

Address used: Pune Railway Station, Sadhu Vaswani Road, Koregaon Park, Pune, Maharashtra, India
Save as: Test

Login: jake@mit.com
Pass: Jake123

**Comment by thesanjeevsharma** [comment]
@prvnbist 🤔 This is because of platform/ngrok thing right? Not code related

**Comment by prvnbist** [comment]
The ngrok server was down when @roshandailykit was testing it, unlikely to happen in production
